import React, { useEffect, useMemo, useRef, useState } from "react";
import { View, Text, StyleSheet, TouchableOpacity, ActivityIndicator, Animated, Easing } from "react-native";
import { Ionicons, MaterialCommunityIcons } from "@expo/vector-icons";
import { COLORS, RADIUS, SPACING, SHADOWS } from "@/constants/theme";

type PrayerName = "Fajr"|"Dhuhr"|"Asr"|"Maghrib"|"Isha";
type PrayerTime = { name: PrayerName; time: Date; label: string };
type LocationDetails = { city:string; state:string; country:string; timezone:string; gmt:string; elevation:string; latitude:number; longitude:number; permission:"idle"|"requesting"|"granted"|"denied"|"unavailable" };
const THEMES=[{accent:"#D4AF37",secondary:"#34D399",bg:"#0f3d35"},{accent:"#F8D77A",secondary:"#93C5FD",bg:"#1e293b"},{accent:"#FDE68A",secondary:"#FED7AA",bg:"#7c2d12"}];
const FALLBACK: LocationDetails={city:"Location unavailable",state:"Permission needed",country:"Using device timezone",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"Local timezone",gmt:"GMT",elevation:"—",latitude:21.4225,longitude:39.8262,permission:"idle"};
const pad=(n:number)=>String(n).padStart(2,"0");
const fmt=(d:Date)=>d.toLocaleTimeString([], {hour:"numeric",minute:"2-digit"});
const hijri=(d:Date)=>new Intl.DateTimeFormat("en-TN-u-ca-islamic",{day:"numeric",month:"long",year:"numeric"}).format(d);
const approx=(date:Date,h:number,m:number)=>{const d=new Date(date);d.setHours(h,m,0,0);return d;};
const calc=(now:Date):PrayerTime[]=>[{name:"Fajr",time:approx(now,5,0),label:fmt(approx(now,5,0))},{name:"Dhuhr",time:approx(now,13,0),label:fmt(approx(now,13,0))},{name:"Asr",time:approx(now,16,30),label:fmt(approx(now,16,30))},{name:"Maghrib",time:approx(now,19,0),label:fmt(approx(now,19,0))},{name:"Isha",time:approx(now,20,30),label:fmt(approx(now,20,30))}];
export default function IslamicDashboardWidget(){
const [now,setNow]=useState(new Date()); const [themeIndex,setThemeIndex]=useState(0); const [loc,setLoc]=useState<LocationDetails>(FALLBACK); const pulse=useRef(new Animated.Value(0)).current;
useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return ()=>clearInterval(t)},[]);
useEffect(()=>{const a=Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1,duration:1200,easing:Easing.inOut(Easing.ease),useNativeDriver:true}),Animated.timing(pulse,{toValue:0,duration:1200,easing:Easing.inOut(Easing.ease),useNativeDriver:true})]));a.start();return ()=>a.stop();},[pulse]);
const theme=THEMES[themeIndex%THEMES.length]; const prayers=useMemo(()=>calc(now),[now]); const current=prayers[0]; const next=prayers[1];
const requestLocation=async()=>{setLoc((p)=>({...p,permission:"requesting"})); try{const Location=require("expo-location"); const perm=await Location.requestForegroundPermissionsAsync(); if(perm.status!=="granted"){setLoc((p)=>({...p,permission:"denied"})); return;} const pos=await Location.getCurrentPositionAsync({}); const rev=await Location.reverseGeocodeAsync({latitude:pos.coords.latitude,longitude:pos.coords.longitude}); const r=rev?.[0]||{}; setLoc({city:r.city||"Unknown city",state:r.region||"Unknown state",country:r.country||"Unknown country",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"Local timezone",gmt:`GMT${new Date().getTimezoneOffset()>0?"-":"+"}${pad(Math.floor(Math.abs(new Date().getTimezoneOffset())/60))}:${pad(Math.abs(new Date().getTimezoneOffset())%60)}`,elevation:typeof pos.coords.altitude==="number"?`${Math.round(pos.coords.altitude)}m`:"—",latitude:pos.coords.latitude,longitude:pos.coords.longitude,permission:"granted"}); } catch {setLoc((p)=>({...p,permission:"unavailable"}));}};
return <View style={[styles.wrap,{backgroundColor:theme.bg}]} testID="islamic-dashboard-widget"><View style={styles.top}><View style={{flex:1}}><Text style={styles.eyebrow}>Islamic Dashboard</Text><Text style={styles.title}>{hijri(now)}</Text></View><TouchableOpacity style={[styles.theme,{borderColor:theme.accent}]} onPress={()=>setThemeIndex((i)=>i+1)}><Ionicons name="color-palette-outline" size={16} color={theme.accent}/><Text style={[styles.themeTxt,{color:theme.accent}]}>Change Theme</Text></TouchableOpacity></View><View style={styles.row}><Animated.View style={[styles.meter,{borderColor:theme.accent,transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[1,1.02]})}]}]}><MaterialCommunityIcons name="mosque" size={30} color={theme.accent}/><Text style={styles.current}>{current.name}</Text><Text style={styles.next}>Next {next.name}</Text></Animated.View><View style={styles.panel}><Text style={styles.loc}>{loc.city}</Text><Text style={styles.meta}>{loc.state} • {loc.country}</Text>{loc.permission!=="granted"?<TouchableOpacity style={styles.locBtn} onPress={requestLocation}>{loc.permission==="requesting"?<ActivityIndicator color="#fff"/>:<Text style={styles.locBtnTxt}>Enable location</Text>}</TouchableOpacity>:null}</View></View><View style={styles.pills}>{prayers.map((p)=><View key={p.name} style={[styles.pill,{borderColor:theme.accent}]}><Text style={[styles.pn,{color:theme.accent}]}>{p.name}</Text><Text style={styles.pt}>{p.label}</Text></View>)}</View></View>
}
const styles=StyleSheet.create({wrap:{marginTop:12,borderRadius:24,padding:SPACING.md,...SHADOWS.card},top:{flexDirection:"row",gap:8},eyebrow:{color:"#ffffffb3",fontSize:11,fontWeight:"800"},title:{color:"#fff",fontSize:16,fontWeight:"800"},theme:{borderWidth:1,borderRadius:RADIUS.full,paddingHorizontal:10,paddingVertical:8,flexDirection:"row",gap:4,alignItems:"center"},themeTxt:{fontSize:11,fontWeight:"700"},row:{marginTop:12,flexDirection:"row",gap:10,alignItems:"stretch"},meter:{width:118,height:118,borderRadius:65,borderWidth:3,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(255,255,255,0.12)"},current:{color:"#fff",fontWeight:"800"},next:{color:"#ffffffcc",fontSize:11},panel:{flex:1,minHeight:118,backgroundColor:"rgba(255,255,255,0.12)",borderRadius:16,padding:10,justifyContent:"center"},loc:{color:"#fff",fontWeight:"700"},meta:{color:"#ffffffcc",fontSize:12,marginTop:4},locBtn:{marginTop:8,backgroundColor:COLORS.primary,borderRadius:RADIUS.full,paddingVertical:8,alignItems:"center"},locBtnTxt:{color:"#fff",fontWeight:"700"},pills:{marginTop:12,flexDirection:"row",flexWrap:"wrap",gap:8},pill:{borderWidth:1,borderRadius:12,paddingHorizontal:8,paddingVertical:6,backgroundColor:"rgba(255,255,255,0.12)"},pn:{fontSize:11,fontWeight:"700"},pt:{color:"#fff",fontSize:11}})
