export const QUIZ_CATEGORIES = [
  "Adab-e-Guftagu",
  "Adab-e-Khana",
  "Adab-e-Libas",
  "Adab-e-Majlis",
  "Adab-e-Masjid",
  "Adab-e-Safar",
  "Adab-e-Sona",
  "Amanatdari",
  "Azan",
  "Bachchon ki Tarbiyat",
  "Ghibat",
  "Ghusl",
  "Haiz",
  "Hasad",
  "Haya",
  "Hijab",
  "Istihaza",
  "Istinja",
  "Libas ke Ahkam",
  "Mahram aur Ghair Mahram",
  "Mehr",
  "Najasat",
  "Namaz Todne Wali Cheezein",
  "Namaz ke Farz",
  "Namaz ke Makruhat",
  "Namaz ke Wajibat",
  "Namaz ki Shartein",
  "Namaz ki Sunnatein",
  "Nifas",
  "Nikah",
  "Roza",
  "Roza Todne Wali Cheezein",
  "Sajda Sahw",
  "Satr-e-Aurat",
  "Shukr",
  "Sidq",
  "Takabbur",
  "Tawakkul",
  "Tawazu",
  "Tawbah",
  "Tayammum",
  "Walidain ke Huqooq",
  "Witr",
  "Wudu"
];
