export const DAILY_WISDOM = [
  { arabic: "فَاذْكُرُونِي أَذْكُرْكُمْ", translation: "So remember Me; I will remember you.", reference: "Surah Al-Baqarah 2:152" },
  { arabic: "إِنَّ مَعَ الْعُسْرِ يُسْرًا", translation: "Indeed, with hardship [will be] ease.", reference: "Surah Ash-Sharh 94:6" },
  { arabic: "وَهُوَ مَعَكُمْ أَيْنَ مَا كُنْتُمْ", translation: "And He is with you wherever you are.", reference: "Surah Al-Hadid 57:4" },
  { arabic: "رَبِّ زِدْنِي عِلْمًا", translation: "My Lord, increase me in knowledge.", reference: "Surah Taha 20:114" },
  { arabic: "وَاللَّهُ يُحِبُّ الْمُحْسِنِينَ", translation: "And Allah loves the doers of good.", reference: "Surah Al Imran 3:134" },
  { arabic: "إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", translation: "Indeed, Allah is with the patient.", reference: "Surah Al-Baqarah 2:153" },
  { arabic: "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا", translation: "Allah does not burden a soul beyond that it can bear.", reference: "Surah Al-Baqarah 2:286" },
  { arabic: "وَمَنْ يَتَّقِ اللَّهَ يَجْعَلْ لَهُ مَخْرَجًا", translation: "And whoever fears Allah, He will make for him a way out.", reference: "Surah At-Talaq 65:2" },
  { arabic: "فَصَبْرٌ جَمِيلٌ", translation: "So patience is most fitting.", reference: "Surah Yusuf 12:83" },
  { arabic: "وَتَوَكَّلْ عَلَى اللَّهِ", translation: "And rely upon Allah.", reference: "Surah Al-Ahzab 33:3" },
  { arabic: "إِنَّ اللَّهَ سَمِيعٌ عَلِيمٌ", translation: "Indeed, Allah is Hearing and Knowing.", reference: "Surah Al-Baqarah 2:181" },
  { arabic: "وَقُلِ الْحَمْدُ لِلَّهِ", translation: "And say, 'Praise to Allah'.", reference: "Surah Al-Isra 17:111" },
  { arabic: "إِنَّ اللَّهَ بِمَا تَعْمَلُونَ بَصِيرٌ", translation: "Indeed, Allah is Seeing of what you do.", reference: "Surah Al-Baqarah 2:110" },
  { arabic: "وَمَا تَوْفِيقِي إِلَّا بِاللَّهِ", translation: "And my success is not but through Allah.", reference: "Surah Hud 11:88" },
  { arabic: "وَاللَّهُ خَيْرُ الرَّازِقِينَ", translation: "And Allah is the best of providers.", reference: "Surah Al-Jumu'ah 62:11" },
  { arabic: "وَأَحْسِنُوا إِنَّ اللَّهَ يُحِبُّ الْمُحْسِنِينَ", translation: "And do good; indeed, Allah loves the doers of good.", reference: "Surah Al-Baqarah 2:195" },
  { arabic: "وَأَنَّ السَّاعَةَ آتِيَةٌ لَا رَيْبَ فِيهَا", translation: "And that the Hour is coming - no doubt about it.", reference: "Surah Al-Hajj 22:7" },
  { arabic: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", translation: "[All] praise is [due] to Allah, Lord of the worlds.", reference: "Surah Al-Fatihah 1:2" },
  { arabic: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ", translation: "Guide us to the straight path.", reference: "Surah Al-Fatihah 1:6" },
  { arabic: "وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا", translation: "And hold firmly to the rope of Allah all together.", reference: "Surah Al Imran 3:103" },
  { arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ", translation: "Say, 'He is Allah, [who is] One'.", reference: "Surah Al-Ikhlas 112:1" },
  { arabic: "اللَّهُ الصَّمَدُ", translation: "Allah, the Eternal Refuge.", reference: "Surah Al-Ikhlas 112:2" },
  { arabic: "وَالضُّحَى", translation: "By the morning brightness.", reference: "Surah Ad-Duhaa 93:1" },
  { arabic: "وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَى", translation: "And your Lord is going to give you, and you will be satisfied.", reference: "Surah Ad-Duhaa 93:5" },
  { arabic: "سَلَامٌ قَوْلًا مِنْ رَبٍّ رَحِيمٍ", translation: "[And] 'Peace,' a word from a Merciful Lord.", reference: "Surah Ya-Sin 36:58" },
];

export const MASNOON_DUAS = [
  { arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا", translation: "O Allah, grant me beneficial knowledge.", reference: "Sunan Ibn Majah" },
  { arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ", translation: "In the name of Allah, I place my trust in Allah.", reference: "Abu Dawud" },
  { arabic: "اللَّهُمَّ اغْفِرْ لِي وَارْحَمْنِي", translation: "O Allah, forgive me and have mercy on me.", reference: "Sahih Muslim" },
  { arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً", translation: "Our Lord, give us in this world [that which is] good.", reference: "Surah Al-Baqarah 2:201" },
  { arabic: "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ", translation: "O Allah, You are Peace and from You is peace.", reference: "Sahih Muslim" },
  { arabic: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ", translation: "O Changer of the hearts, make my heart firm upon Your religion.", reference: "Jami at-Tirmidhi" },
  { arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ", translation: "I seek refuge in Allah from the outcast Shaitan.", reference: "Quran" },
  { arabic: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي", translation: "O Allah, You are forgiving and love forgiveness, so forgive me.", reference: "Jami at-Tirmidhi" },
  { arabic: "بِسْمِ اللهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ", translation: "In the Name of Allah, with whose Name nothing is harmed.", reference: "Abu Dawud" },
  { arabic: "رَضِيتُ بِاللَّهِ رَبًّا وَبِالْإِسْلَامِ دِينًا", translation: "I am pleased with Allah as my Lord, and with Islam as my religion.", reference: "Abu Dawud" },
  { arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", translation: "Glory is to Allah and praise is to Him.", reference: "Sahih Bukhari" },
  { arabic: "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ", translation: "I seek the forgiveness of Allah and repent to Him.", reference: "Sahih Bukhari" },
  { arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيمَا رَزَقْتَنَا", translation: "O Allah, bless for us what You have provided us.", reference: "Hisn al-Muslim" },
  { arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا", translation: "Praise be to Allah Who has fed us and given us drink.", reference: "Abu Dawud" },
  { arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي", translation: "O Allah, grant me health in my body.", reference: "Abu Dawud" },
  { arabic: "حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ", translation: "Sufficient for me is Allah; there is no deity except Him.", reference: "Surah At-Tawbah 9:129" },
  { arabic: "اللَّهُمَّ نَقِّنِي مِنَ الْخَطَايَا", translation: "O Allah, cleanse me of my transgressions.", reference: "Sahih Muslim" },
  { arabic: "رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ", translation: "My Lord, forgive me and my parents.", reference: "Surah Nuh 71:28" },
  { arabic: "رَبِّ هَبْ لِي حُكْمًا وَأَلْحِقْنِي بِالصَّالِحِينَ", translation: "My Lord, grant me authority and join me with the righteous.", reference: "Surah Ash-Shu'ara 26:83" },
  { arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ", translation: "O Allah, I seek refuge in You from anxiety and sorrow.", reference: "Sahih Bukhari" },
  { arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", translation: "There is no power nor strength except by Allah.", reference: "Sahih Bukhari" },
  { arabic: "سُبْحَانَ اللَّهِ الْعَظِيمِ", translation: "Glory be to Allah, the Supreme.", reference: "Sahih Bukhari" },
  { arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ", translation: "O Allah, send blessings upon Muhammad.", reference: "Al-Ahzab 33:56" },
  { arabic: "رَبِّ إِنِّي ظَلَمْتُ نَفْسِي فَاغْفِرْ لِي", translation: "My Lord, indeed I have wronged myself, so forgive me.", reference: "Surah Al-Qasas 28:16" },
  { arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ", translation: "O Allah, open for me the gates of Your mercy.", reference: "Sahih Muslim" },
];

export const HADITHS = [
  { arabic: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ", translation: "The best among you are those who learn the Qur'an and teach it.", reference: "Sahih al-Bukhari" },
  { arabic: "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ", translation: "Actions are but by intentions.", reference: "Sahih al-Bukhari" },
  { arabic: "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ", translation: "A Muslim is the one from whose tongue and hands the Muslims are safe.", reference: "Sahih al-Bukhari" },
  { arabic: "الدِّينُ النَّصِيحَةُ", translation: "Religion is sincerity.", reference: "Sahih Muslim" },
  { arabic: "الطهور شطر الإيمان", translation: "Purity is half of faith.", reference: "Sahih Muslim" },
  { arabic: "لا يَرْحَمُ اللَّهُ مَنْ لا يَرْحَمُ النَّاسَ", translation: "Allah will not be merciful to those who are not merciful to mankind.", reference: "Sahih al-Bukhari" },
  { arabic: "مَنْ صَمَتَ نَجَا", translation: "He who keeps silent saves himself.", reference: "Jami at-Tirmidhi" },
  { arabic: "الكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ", translation: "A good word is charity.", reference: "Sahih al-Bukhari" },
  { arabic: "الظُّلْمُ ظُلُمَاتٌ يَوْمَ الْقِيَامَةِ", translation: "Oppression will be a darkness on the Day of Resurrection.", reference: "Sahih al-Bukhari" },
  { arabic: "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ", translation: "Smiling in the face of your brother is charity.", reference: "Jami at-Tirmidhi" },
  { arabic: "مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ", translation: "Charity does not decrease wealth.", reference: "Sahih Muslim" },
  { arabic: "لا تَغْضَبْ", translation: "Do not become angry.", reference: "Sahih al-Bukhari" },
  { arabic: "يَسِّرُوا وَلا تُعَسِّرُوا", translation: "Make things easy and do not make things difficult.", reference: "Sahih al-Bukhari" },
  { arabic: "مَنْ غَشَّنَا فَلَيْسَ مِنَّا", translation: "Whoever deceives us is not one of us.", reference: "Sahih Muslim" },
  { arabic: "الحَيَاءُ شُعْبَةٌ مِنَ الإِيمَانِ", translation: "Modesty is a branch of faith.", reference: "Sahih Muslim" },
  { arabic: "السِّوَاكُ مَطْهَرَةٌ لِلْفَمِ مَرْضَاةٌ لِلرَّبِّ", translation: "Miswak purifies the mouth and pleases the Lord.", reference: "Sunan an-Nasa'i" },
  { arabic: "الدُّنْيَا سِجْنُ الْمُؤْمِنِ وَجَنَّةُ الْكَافِرِ", translation: "The world is a prison for the believer and a paradise for the unbeliever.", reference: "Sahih Muslim" },
  { arabic: "اقْرَءُوا الْقُرْآنَ فَإِنَّهُ يَأْتِي يَوْمَ الْقِيَامَةِ شَفِيعًا", translation: "Read the Quran, for it will come as an intercessor on the Day of Resurrection.", reference: "Sahih Muslim" },
  { arabic: "الصَّلَوَاتُ الْخَمْسُ كَفَّارَةٌ لِمَا بَيْنَهُنَّ", translation: "The five daily prayers expiate the sins committed between them.", reference: "Sahih Muslim" },
  { arabic: "طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ", translation: "Seeking knowledge is an obligation upon every Muslim.", reference: "Sunan Ibn Majah" },
  { arabic: "الْمَرْءُ مَعَ مَنْ أَحَبَّ", translation: "A person will be with whom he loves.", reference: "Sahih al-Bukhari" },
  { arabic: "خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ", translation: "The best of people are those that bring most benefit to the rest of mankind.", reference: "Daraqutni" },
  { arabic: "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ", translation: "None of you truly believes until he loves for his brother what he loves for himself.", reference: "Sahih al-Bukhari" },
  { arabic: "اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ", translation: "Fear Allah wherever you are.", reference: "Jami at-Tirmidhi" },
  { arabic: "كُلُّ مَعْرُوفٍ صَدَقَةٌ", translation: "Every act of goodness is charity.", reference: "Sahih Muslim" },
];

export const MOTIVATIONAL_QUOTES = [
  { text: "Knowledge is the life of the mind." },
  { text: "Patience is a pillar of faith." },
  { text: "The first step to knowledge is listening." },
  { text: "Seek knowledge from the cradle to the grave." },
  { text: "Character is built through consistency." },
  { text: "Gratitude turns what we have into enough." },
  { text: "Trust Allah's timing." },
  { text: "Success is the result of sincere effort." },
  { text: "Do not lose hope, nor be sad." },
  { text: "A beautiful character outweighs a beautiful face." },
  { text: "Hardship is often a blessing in disguise." },
  { text: "Sincerity is the soul of every good deed." },
  { text: "Forgive others as you wish to be forgiven." },
  { text: "Humility elevates the soul." },
  { text: "Every difficulty brings an opportunity to rely on Allah." },
  { text: "Small consistent deeds are better than grand inconsistent ones." },
  { text: "Prayer is the key to all treasures." },
  { text: "A grateful heart is a magnet for miracles." },
  { text: "Tawakkul is knowing Allah will take care of the rest." },
  { text: "Your time is limited; spend it on what truly matters." },
  { text: "Good manners are the essence of Islamic teaching." },
  { text: "Knowledge without action is like a tree without fruit." },
  { text: "The strongest among you is the one who controls his anger." },
  { text: "Every morning is a new chance to do good." },
  { text: "Let your faith be bigger than your fears." },
];
