import { QuranAyat, SurahData } from './quranApi';

export const STARTER_SURAHS: Record<number, SurahData> = {
  1: {
    surahNumber: 1,
    surahName: 'Al-Fatihah',
    arabicName: 'الفاتحة',
    totalAyat: 7,
    fetchedAt: 1700000000000,
    ayats: [
      {
        number: 1,
        globalNumber: 1,
        arabic: 'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
        roman: 'Bismillāhir-Raḥmānir-Raḥīm',
        urduMeaning: 'اللہ کے نام سے جو رحمان و رحیم ہے',
        surahNumber: 1,
        surahName: 'Al-Fatihah',
      },
      {
        number: 2,
        globalNumber: 2,
        arabic: 'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ',
        roman: 'Al-ḥamdu lillāhi Rabbil-ʻālamīn',
        urduMeaning: 'سب تعریفیں اللہ ہی کے لیے ہیں جو تمام جہانوں کا پالنے والا ہے',
        surahNumber: 1,
        surahName: 'Al-Fatihah',
      },
      {
        number: 3,
        globalNumber: 3,
        arabic: 'ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
        roman: 'Ar-Raḥmānir-Raḥīm',
        urduMeaning: 'بڑا مہربان، نہایت رحم والا',
        surahNumber: 1,
        surahName: 'Al-Fatihah',
      },
      {
        number: 4,
        globalNumber: 4,
        arabic: 'مَـٰلِكِ يَوْمِ ٱلدِّينِ',
        roman: 'Māliki Yawmid-Dīn',
        urduMeaning: 'روزِ جزا کا مالک',
        surahNumber: 1,
        surahName: 'Al-Fatihah',
      },
      {
        number: 5,
        globalNumber: 5,
        arabic: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
        roman: 'Iyyāka naʻbudu wa iyyāka nastaʻīn',
        urduMeaning: 'ہم صرف تیری ہی عبادت کرتے ہیں اور صرف تجھ ہی سے مدد مانگتے ہیں',
        surahNumber: 1,
        surahName: 'Al-Fatihah',
      },
      {
        number: 6,
        globalNumber: 6,
        arabic: 'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ',
        roman: 'Ihdinaṣ-ṣirāṭal-mustaqīm',
        urduMeaning: 'ہمیں سیدھے راستے کی ہدایت فرما',
        surahNumber: 1,
        surahName: 'Al-Fatihah',
      },
      {
        number: 7,
        globalNumber: 7,
        arabic: 'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
        roman: 'Ṣirāṭallaḏīna anʻamta ʻalayhim ghayril-maghḍūbi ʻalayhim walad-ḍāllīn',
        urduMeaning: 'ان لوگوں کا راستہ جن پر تو نے انعام فرمایا، نہ کہ ان کا جن پر غضب ہوا اور نہ گمراہوں کا',
        surahNumber: 1,
        surahName: 'Al-Fatihah',
      },
    ],
  },
  112: {
    surahNumber: 112,
    surahName: 'Al-Ikhlas',
    arabicName: 'الإخلاص',
    totalAyat: 4,
    fetchedAt: 1700000000000,
    ayats: [
      {
        number: 1,
        globalNumber: 6222,
        arabic: 'قُلْ هُوَ ٱللَّهُ أَحَدٌ',
        roman: 'Qul huwal-lāhu aḥad',
        urduMeaning: 'آپ فرما دیجیے کہ وہ اللہ ایک ہے',
        surahNumber: 112,
        surahName: 'Al-Ikhlas',
      },
      {
        number: 2,
        globalNumber: 6223,
        arabic: 'ٱللَّهُ ٱلصَّمَدُ',
        roman: 'Allāhuṣ-ṣamad',
        urduMeaning: 'اللہ بے نیاز ہے (سب اس کے محتاج ہیں)',
        surahNumber: 112,
        surahName: 'Al-Ikhlas',
      },
      {
        number: 3,
        globalNumber: 6224,
        arabic: 'لَمْ يَلِدْ وَلَمْ يُولَدْ',
        roman: 'Lam yalid wa lam yūlad',
        urduMeaning: 'نہ اس سے کوئی پیدا ہوا اور نہ وہ کسی سے پیدا ہوا',
        surahNumber: 112,
        surahName: 'Al-Ikhlas',
      },
      {
        number: 4,
        globalNumber: 6225,
        arabic: 'وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ',
        roman: 'Wa lam yakul-lahū kufuwan aḥad',
        urduMeaning: 'اور کوئی اس کا ہمسر نہیں ہے',
        surahNumber: 112,
        surahName: 'Al-Ikhlas',
      },
    ],
  },
  113: {
    surahNumber: 113,
    surahName: 'Al-Falaq',
    arabicName: 'الفلق',
    totalAyat: 5,
    fetchedAt: 1700000000000,
    ayats: [
      {
        number: 1,
        globalNumber: 6226,
        arabic: 'قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ',
        roman: 'Qul aʻūḏu birabbil-falaq',
        urduMeaning: 'آپ فرما دیجیے کہ میں صبح کے رب کی پناہ مانگتا ہوں',
        surahNumber: 113,
        surahName: 'Al-Falaq',
      },
      {
        number: 2,
        globalNumber: 6227,
        arabic: 'مِن شَرِّ مَا خَلَقَ',
        roman: 'Min sharri mā khalaq',
        urduMeaning: 'ہر اس چیز کے شر سے جو اس نے پیدا کی',
        surahNumber: 113,
        surahName: 'Al-Falaq',
      },
      {
        number: 3,
        globalNumber: 6228,
        arabic: 'وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ',
        roman: 'Wa min sharri ghāsiqin iḏā waqab',
        urduMeaning: 'اور اندھیری رات کے شر سے جب وہ چھا جائے',
        surahNumber: 113,
        surahName: 'Al-Falaq',
      },
      {
        number: 4,
        globalNumber: 6229,
        arabic: 'وَمِن شَرِّ ٱلنَّفَّـٰثَـٰتِ فِى ٱلْعُقَدِ',
        roman: 'Wa min sharrin-naffāthāti fīl-ʻuqad',
        urduMeaning: 'اور گرہوں میں پھونکنے والیوں کے شر سے',
        surahNumber: 113,
        surahName: 'Al-Falaq',
      },
      {
        number: 5,
        globalNumber: 6230,
        arabic: 'وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
        roman: 'Wa min sharri ḥāsidin iḏā ḥasad',
        urduMeaning: 'اور حسد کرنے والے کے شر سے جب وہ حسد کرے',
        surahNumber: 113,
        surahName: 'Al-Falaq',
      },
    ],
  },
  114: {
    surahNumber: 114,
    surahName: 'An-Nas',
    arabicName: 'الناس',
    totalAyat: 6,
    fetchedAt: 1700000000000,
    ayats: [
      {
        number: 1,
        globalNumber: 6231,
        arabic: 'قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ',
        roman: 'Qul aʻūḏu birabbin-nās',
        urduMeaning: 'آپ فرما دیجیے کہ میں انسانوں کے پروردگار کی پناہ مانگتا ہوں',
        surahNumber: 114,
        surahName: 'An-Nas',
      },
      {
        number: 2,
        globalNumber: 6232,
        arabic: 'مَلِكِ ٱلنَّاسِ',
        roman: 'Malikin-nās',
        urduMeaning: 'جو انسانوں کا بادشاہ ہے',
        surahNumber: 114,
        surahName: 'An-Nas',
      },
      {
        number: 3,
        globalNumber: 6233,
        arabic: 'إِلَـٰهِ ٱلنَّاسِ',
        roman: 'Ilāhin-nās',
        urduMeaning: 'جو انسانوں کا معبودِ برحق ہے',
        surahNumber: 114,
        surahName: 'An-Nas',
      },
      {
        number: 4,
        globalNumber: 6234,
        arabic: 'مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ',
        roman: 'Min sharril-waswāsil-khannās',
        urduMeaning: 'وسوسہ ڈالنے والے، پیچھے ہٹ جانے والے کے شر سے',
        surahNumber: 114,
        surahName: 'An-Nas',
      },
      {
        number: 5,
        globalNumber: 6235,
        arabic: 'ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ',
        roman: 'Allaḏī yuwaswisu fī ṣudūrin-nās',
        urduMeaning: 'جو لوگوں کے سینوں میں وسوسے ڈالتا ہے',
        surahNumber: 114,
        surahName: 'An-Nas',
      },
      {
        number: 6,
        globalNumber: 6236,
        arabic: 'مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ',
        roman: 'Minal-jinnati wan-nās',
        urduMeaning: 'خواہ وہ جنات میں سے ہو یا انسانوں میں سے',
        surahNumber: 114,
        surahName: 'An-Nas',
      },
    ],
  },
};
